### ISSUE TITLE
Migrate ICS feature to a complete app

### ISSUE THREAD

**Issue by julienrbrt** [ignite/apps#101]
Currently the Ignite consumer app is a sort of `fake` app. It exists only for not importing ICS in ignite/cli.
However, the templates are still in ignite cli.
We should totally movec the templating logic from ICS to the consumer app (maybe rename to ics).
This way we can iterate faster on the ICS app, without risking getting block on Informal at the next SDK version upgrade.

**Comment by julienrbrt** [comment]
Additionally we should edit the config.yml with good defaults:

- Remove `validators` entry
- Add genesis modifications:

<details>
<summary>Modifications</summary>

```yaml
genesis:
  chain_id: ccv-1
  genesis_time: "2024-08-02T09:04:18.804524734Z" # must match spawn time in genesis proposal
  app_state:
    ccvconsumer:
      provider:
        client_state:
          chain-id: provider
    slashing:
      params:
        signed_blocks_window: 20000
        min_signed_per_window: "0.5"
```
</details>
